{
  "formatVersion": "1.1",
  "component": {
    "group": "me.rime.symbols",
    "module": "init-annotation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-annotation-1.0.0.jar",
          "url": "init-annotation-1.0.0.jar",
          "size": 1463,
          "sha512": "1141d5fd38b1d82dfccc3dc1f5fea36cd61a8c92eae88d59d2974f37b06dcb2e5c076e61cfe3fd5d5134e2f4a9e757cc9988c82e4e6e8e1c699d9bb5da4bcbda",
          "sha256": "1e4186d2f9cf46e5b643d9b73911a5c7f8869b44b5bf0c392c56c4e455f3fa53",
          "sha1": "fbb5294c1b459bdca2c8e3a9003dac75fa48ad1a",
          "md5": "a8ba4423a470e9b38fb99a48c1aa2b21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-annotation-1.0.0.jar",
          "url": "init-annotation-1.0.0.jar",
          "size": 1463,
          "sha512": "1141d5fd38b1d82dfccc3dc1f5fea36cd61a8c92eae88d59d2974f37b06dcb2e5c076e61cfe3fd5d5134e2f4a9e757cc9988c82e4e6e8e1c699d9bb5da4bcbda",
          "sha256": "1e4186d2f9cf46e5b643d9b73911a5c7f8869b44b5bf0c392c56c4e455f3fa53",
          "sha1": "fbb5294c1b459bdca2c8e3a9003dac75fa48ad1a",
          "md5": "a8ba4423a470e9b38fb99a48c1aa2b21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "init-annotation-1.0.0-sources.jar",
          "url": "init-annotation-1.0.0-sources.jar",
          "size": 1062,
          "sha512": "7f787916cdf734dd211de803dbbe85315e14428132b5184bd9b51b38657a1cdbaf9be314760d67f588ad754582080f0c0083671bec6e5ae6444daeda3eeb1082",
          "sha256": "5b5c9a3277be0e1e8ec049cc8249855ab0e392cc5c1aa1c0782a256a4767ee46",
          "sha1": "04364d584c8672e05fc2f44bd59cc9f64bf8dcd1",
          "md5": "f592507c8f196b5b10d1e18502578f01"
        }
      ]
    }
  ]
}
