{
  "formatVersion": "1.1",
  "component": {
    "group": "me.rime.symbols",
    "module": "init-processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-processor-1.0.0.jar",
          "url": "init-processor-1.0.0.jar",
          "size": 9808,
          "sha512": "38916f51d8d6ee76491c90328bf00fc233cfb6fb3ebf78a99b0026fdeb865d03b7befa26356937980a37b82301f1ee9eebc55737de78e81b7dc2115db728d494",
          "sha256": "629ad9a62cc239d5516846c1ecf3d0bfb047d128dee91f4e392cd6969af52c0d",
          "sha1": "35696e828c1c66f23c2c923429555082523cfd86",
          "md5": "25c234d2d003779fe4d6fda766803473"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.10-1.0.29"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "me.rime.symbols",
          "module": "init-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-processor-1.0.0.jar",
          "url": "init-processor-1.0.0.jar",
          "size": 9808,
          "sha512": "38916f51d8d6ee76491c90328bf00fc233cfb6fb3ebf78a99b0026fdeb865d03b7befa26356937980a37b82301f1ee9eebc55737de78e81b7dc2115db728d494",
          "sha256": "629ad9a62cc239d5516846c1ecf3d0bfb047d128dee91f4e392cd6969af52c0d",
          "sha1": "35696e828c1c66f23c2c923429555082523cfd86",
          "md5": "25c234d2d003779fe4d6fda766803473"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "init-processor-1.0.0-sources.jar",
          "url": "init-processor-1.0.0-sources.jar",
          "size": 3005,
          "sha512": "dc25acb07ccf668e8e0815282b18a9165e2c8b6c41e8a3b229ee9feca8bf59ccc12f61b277cf1bf0df4be51521d504a0c7ccfe18f2305c4a376ea075442bac12",
          "sha256": "6c010c75c4a2f8c0bbd3b262334d01fcb03d41e3cb3eaa809590b8e9239e8c90",
          "sha1": "7db9c58da51b976607b2278d7c91dce039e09c04",
          "md5": "f4f99b9266b2c3a5708fc6670e6a0e8c"
        }
      ]
    }
  ]
}
