{
  "formatVersion": "1.1",
  "component": {
    "group": "me.rime.symbols",
    "module": "init-processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-processor-1.0.0.jar",
          "url": "init-processor-1.0.0.jar",
          "size": 9808,
          "sha512": "ca6e464701b0ad3de349433096d654bbe6013da69b2cbbb53b9862427031dd057d7380c93c4d9fd8d237b62d74762d4935de5694932a101f8cc9003e1b1bf3ac",
          "sha256": "1d0878b7f6553c428d856c765a03c8fd373ecaade4f0b3d65bd134786889bd99",
          "sha1": "05731f7bf9e8a3bb1303fbf2dcce7f609de3f326",
          "md5": "38948848928349fd4310500962698dc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.10-1.0.29"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "me.rime.symbols",
          "module": "init-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-processor-1.0.0.jar",
          "url": "init-processor-1.0.0.jar",
          "size": 9808,
          "sha512": "ca6e464701b0ad3de349433096d654bbe6013da69b2cbbb53b9862427031dd057d7380c93c4d9fd8d237b62d74762d4935de5694932a101f8cc9003e1b1bf3ac",
          "sha256": "1d0878b7f6553c428d856c765a03c8fd373ecaade4f0b3d65bd134786889bd99",
          "sha1": "05731f7bf9e8a3bb1303fbf2dcce7f609de3f326",
          "md5": "38948848928349fd4310500962698dc7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "init-processor-1.0.0-sources.jar",
          "url": "init-processor-1.0.0-sources.jar",
          "size": 3005,
          "sha512": "bba0cfaf980986cc0e4a7b01554221981fb9c60c20c7963db25ecf37bbfe3fc8f81f1c6defddb8616db23771c52ffc53420b9dd46d21ee092c91f3f999d07236",
          "sha256": "c0e53e8023abb3015352a8d15c5d90e9a37a1544124a3aad2b4d3d8137972f5c",
          "sha1": "6d6078bda1b7c3be12db45ee5965d73f61d9461a",
          "md5": "4ae41d51f80b496e47fbfdc24d93ff02"
        }
      ]
    }
  ]
}
