{
  "formatVersion": "1.1",
  "component": {
    "group": "me.rime.symbols",
    "module": "init-processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-processor-1.0.0.jar",
          "url": "init-processor-1.0.0.jar",
          "size": 9808,
          "sha512": "9f47a64b14782eba4dacbb0a32d85517b06f21fa9b42a68a515180edef3b69fc1eceb2cac123bfaaf6c61148d3dfdcd09bf075fa97a805cda9fe29109c5cf927",
          "sha256": "16914bac43cc73e40098b673f7c05ce7ebd0d1284b2b58a7b95b0fd02e77be9b",
          "sha1": "71534d53c2b8c0adefa1c2a5d0c27c513dce8855",
          "md5": "33bf74221cb4a1a71dfc5e0fadaa6ad9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.10-1.0.29"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "me.rime.symbols",
          "module": "init-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "init-processor-1.0.0.jar",
          "url": "init-processor-1.0.0.jar",
          "size": 9808,
          "sha512": "9f47a64b14782eba4dacbb0a32d85517b06f21fa9b42a68a515180edef3b69fc1eceb2cac123bfaaf6c61148d3dfdcd09bf075fa97a805cda9fe29109c5cf927",
          "sha256": "16914bac43cc73e40098b673f7c05ce7ebd0d1284b2b58a7b95b0fd02e77be9b",
          "sha1": "71534d53c2b8c0adefa1c2a5d0c27c513dce8855",
          "md5": "33bf74221cb4a1a71dfc5e0fadaa6ad9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "init-processor-1.0.0-sources.jar",
          "url": "init-processor-1.0.0-sources.jar",
          "size": 3005,
          "sha512": "e71f7128dddf17e6d2e67e052cdd1531c786875e9b8185b6268e039f93e826d8fbf9311fcfe0dc2367d387db645c2dd99dfa90834a9e1eebe1e1d2db49e1ad0d",
          "sha256": "de5f87b8dbc5261b6ab9c7c683d4d62b5c5223a6bc40ac8661dea2dc28793cf8",
          "sha1": "48c65282b777b5b71d050fd8381f07fe1099f217",
          "md5": "58f67768c243218d767f74fc70c42fae"
        }
      ]
    }
  ]
}
